### ISSUE TITLE
Plugin Maintainer

### ISSUE THREAD

**Issue by mintsoft** [mintsoft/plugin.video.curiositystream#1]
@GMaxera I'm happy to take over this plugin as the "official maintainer" if you're happy to let it go? 

Otherwise I've got a fix that I'd like to incorporate but I can't figure out a way to be able to create a clean PR into the repo you currently seem to be using: https://github.com/GMaxera/repo-plugins

**Comment by GMaxera** [comment]
@mintsoft Yes, I'm happy to let you take over.
Thank you for offering yourself as new maintainer.

Let me know if you need anything from me to take over the plugin.
